/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressRequest
 */
export interface AddressRequest {
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    lineOne: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    lineTwo?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    lineThree?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    cityTown?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    provinceDistrict?: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    postCode: string;
    /**
     * 
     * @type {string}
     * @memberof AddressRequest
     */
    country: string;
}

export function AddressRequestFromJSON(json: any): AddressRequest {
    return AddressRequestFromJSONTyped(json, false);
}

export function AddressRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lineOne': json['line_one'],
        'lineTwo': !exists(json, 'line_two') ? undefined : json['line_two'],
        'lineThree': !exists(json, 'line_three') ? undefined : json['line_three'],
        'cityTown': !exists(json, 'city_town') ? undefined : json['city_town'],
        'provinceDistrict': !exists(json, 'province_district') ? undefined : json['province_district'],
        'postCode': json['post_code'],
        'country': json['country'],
    };
}

export function AddressRequestToJSON(value?: AddressRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'line_one': value.lineOne,
        'line_two': value.lineTwo,
        'line_three': value.lineThree,
        'city_town': value.cityTown,
        'province_district': value.provinceDistrict,
        'post_code': value.postCode,
        'country': value.country,
    };
}

