/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClassRequest
 */
export interface ClassRequest {
    /**
     * 
     * @type {string}
     * @memberof ClassRequest
     */
    name: string;
}

export function ClassRequestFromJSON(json: any): ClassRequest {
    return ClassRequestFromJSONTyped(json, false);
}

export function ClassRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function ClassRequestToJSON(value?: ClassRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

