/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating a record sheet for a specific student.
 * @export
 * @interface ClassRecordSheetRequest
 */
export interface ClassRecordSheetRequest {
    /**
     * 
     * @type {number}
     * @memberof ClassRecordSheetRequest
     */
    classId: number;
    /**
     * 
     * @type {number}
     * @memberof ClassRecordSheetRequest
     */
    subjectLevelId: number | null;
    /**
     * 
     * @type {Date}
     * @memberof ClassRecordSheetRequest
     */
    startDate: Date;
    /**
     * 
     * @type {number}
     * @memberof ClassRecordSheetRequest
     */
    numDays?: number;
    /**
     * 
     * @type {number}
     * @memberof ClassRecordSheetRequest
     */
    sheetsPerDay?: number;
    /**
     * 
     * @type {string}
     * @memberof ClassRecordSheetRequest
     */
    type: string;
}

export function ClassRecordSheetRequestFromJSON(json: any): ClassRecordSheetRequest {
    return ClassRecordSheetRequestFromJSONTyped(json, false);
}

export function ClassRecordSheetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClassRecordSheetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'classId': json['class_id'],
        'subjectLevelId': json['subject_level_id'],
        'startDate': (new Date(json['start_date'])),
        'numDays': !exists(json, 'num_days') ? undefined : json['num_days'],
        'sheetsPerDay': !exists(json, 'sheets_per_day') ? undefined : json['sheets_per_day'],
        'type': json['type'],
    };
}

export function ClassRecordSheetRequestToJSON(value?: ClassRecordSheetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'class_id': value.classId,
        'subject_level_id': value.subjectLevelId,
        'start_date': (value.startDate.toISOString().substr(0,10)),
        'num_days': value.numDays,
        'sheets_per_day': value.sheetsPerDay,
        'type': value.type,
    };
}

