/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudentList,
    StudentListFromJSON,
    StudentListFromJSONTyped,
    StudentListToJSON,
} from './StudentList';

/**
 * 
 * @export
 * @interface ContactGetStudents
 */
export interface ContactGetStudents {
    /**
     * 
     * @type {StudentList}
     * @memberof ContactGetStudents
     */
    studentId: StudentList;
    /**
     * 
     * @type {string}
     * @memberof ContactGetStudents
     */
    relationship: string;
}

export function ContactGetStudentsFromJSON(json: any): ContactGetStudents {
    return ContactGetStudentsFromJSONTyped(json, false);
}

export function ContactGetStudentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactGetStudents {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'studentId': StudentListFromJSON(json['student_id']),
        'relationship': json['relationship'],
    };
}

export function ContactGetStudentsToJSON(value?: ContactGetStudents | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student_id': StudentListToJSON(value.studentId),
        'relationship': value.relationship,
    };
}

