/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum GradeEnum {
    K = 'K',
    _1 = '1',
    _2 = '2',
    _3 = '3',
    _4 = '4',
    _5 = '5',
    _6 = '6',
    _7 = '7',
    _8 = '8',
    _9 = '9',
    _10 = '10',
    _11 = '11',
    _12 = '12',
    _13 = '13'
}

export function GradeEnumFromJSON(json: any): GradeEnum {
    return GradeEnumFromJSONTyped(json, false);
}

export function GradeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GradeEnum {
    return json as GradeEnum;
}

export function GradeEnumToJSON(value?: GradeEnum | null): any {
    return value as any;
}

