/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemLoanLog
 */
export interface ItemLoanLog {
    /**
     * 
     * @type {number}
     * @memberof ItemLoanLog
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanLog
     */
    itemId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanLog
     */
    studentId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanLog
     */
    quantityLent: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanLog
     */
    quantityReturned: number;
    /**
     * 
     * @type {Date}
     * @memberof ItemLoanLog
     */
    loanDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof ItemLoanLog
     */
    readonly createdAt: Date;
}

export function ItemLoanLogFromJSON(json: any): ItemLoanLog {
    return ItemLoanLogFromJSONTyped(json, false);
}

export function ItemLoanLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemLoanLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': !exists(json, 'item_id') ? undefined : json['item_id'],
        'studentId': !exists(json, 'student_id') ? undefined : json['student_id'],
        'quantityLent': json['quantity_lent'],
        'quantityReturned': json['quantity_returned'],
        'loanDatetime': (new Date(json['loan_datetime'])),
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ItemLoanLogToJSON(value?: ItemLoanLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'student_id': value.studentId,
        'quantity_lent': value.quantityLent,
        'quantity_returned': value.quantityReturned,
        'loan_datetime': (value.loanDatetime.toISOString()),
    };
}

