/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemWithdrawRequest
 */
export interface ItemWithdrawRequest {
    /**
     * 
     * @type {number}
     * @memberof ItemWithdrawRequest
     */
    staffId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemWithdrawRequest
     */
    quantity: number;
}

export function ItemWithdrawRequestFromJSON(json: any): ItemWithdrawRequest {
    return ItemWithdrawRequestFromJSONTyped(json, false);
}

export function ItemWithdrawRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemWithdrawRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'staffId': json['staff_id'],
        'quantity': json['quantity'],
    };
}

export function ItemWithdrawRequestToJSON(value?: ItemWithdrawRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'staff_id': value.staffId,
        'quantity': value.quantity,
    };
}

