/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LendableItemEdit
 */
export interface LendableItemEdit {
    /**
     * 
     * @type {number}
     * @memberof LendableItemEdit
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof LendableItemEdit
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LendableItemEdit
     */
    quantityAvailable?: number;
}

export function LendableItemEditFromJSON(json: any): LendableItemEdit {
    return LendableItemEditFromJSONTyped(json, false);
}

export function LendableItemEditFromJSONTyped(json: any, ignoreDiscriminator: boolean): LendableItemEdit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'quantityAvailable': !exists(json, 'quantity_available') ? undefined : json['quantity_available'],
    };
}

export function LendableItemEditToJSON(value?: LendableItemEdit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'quantity_available': value.quantityAvailable,
    };
}

