/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StatusEnum,
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
} from './StatusEnum';

/**
 * 
 * @export
 * @interface LessonSetAttendanceRequest
 */
export interface LessonSetAttendanceRequest {
    /**
     * 
     * @type {number}
     * @memberof LessonSetAttendanceRequest
     */
    student: number;
    /**
     * 
     * @type {StatusEnum}
     * @memberof LessonSetAttendanceRequest
     */
    status: StatusEnum;
}

export function LessonSetAttendanceRequestFromJSON(json: any): LessonSetAttendanceRequest {
    return LessonSetAttendanceRequestFromJSONTyped(json, false);
}

export function LessonSetAttendanceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LessonSetAttendanceRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'student': json['student'],
        'status': StatusEnumFromJSON(json['status']),
    };
}

export function LessonSetAttendanceRequestToJSON(value?: LessonSetAttendanceRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student': value.student,
        'status': StatusEnumToJSON(value.status),
    };
}

