/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Class,
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
} from './Class';
import {
    Subject,
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';
import {
    SubjectGetLevel,
    SubjectGetLevelFromJSON,
    SubjectGetLevelFromJSONTyped,
    SubjectGetLevelToJSON,
} from './SubjectGetLevel';

/**
 * 
 * @export
 * @interface LessonView
 */
export interface LessonView {
    /**
     * 
     * @type {number}
     * @memberof LessonView
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof LessonView
     */
    startDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof LessonView
     */
    endDatetime: Date;
    /**
     * 
     * @type {Class}
     * @memberof LessonView
     */
    classFk: Class;
    /**
     * 
     * @type {Subject}
     * @memberof LessonView
     */
    readonly subject: Subject | null;
    /**
     * 
     * @type {SubjectGetLevel}
     * @memberof LessonView
     */
    subjectLevel: SubjectGetLevel;
    /**
     * 
     * @type {Date}
     * @memberof LessonView
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof LessonView
     */
    readonly lastModifiedAt: Date;
}

export function LessonViewFromJSON(json: any): LessonView {
    return LessonViewFromJSONTyped(json, false);
}

export function LessonViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): LessonView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDatetime': (new Date(json['start_datetime'])),
        'endDatetime': (new Date(json['end_datetime'])),
        'classFk': ClassFromJSON(json['class_fk']),
        'subject': SubjectFromJSON(json['subject']),
        'subjectLevel': SubjectGetLevelFromJSON(json['subject_level']),
        'createdAt': (new Date(json['created_at'])),
        'lastModifiedAt': (new Date(json['last_modified_at'])),
    };
}

export function LessonViewToJSON(value?: LessonView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_datetime': (value.startDatetime.toISOString()),
        'end_datetime': (value.endDatetime.toISOString()),
        'class_fk': ClassToJSON(value.classFk),
        'subject_level': SubjectGetLevelToJSON(value.subjectLevel),
    };
}

