/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudentList,
    StudentListFromJSON,
    StudentListFromJSONTyped,
    StudentListToJSON,
} from './StudentList';

/**
 * 
 * @export
 * @interface PaginatedStudentListList
 */
export interface PaginatedStudentListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedStudentListList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStudentListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStudentListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<StudentList>}
     * @memberof PaginatedStudentListList
     */
    results?: Array<StudentList>;
}

export function PaginatedStudentListListFromJSON(json: any): PaginatedStudentListList {
    return PaginatedStudentListListFromJSONTyped(json, false);
}

export function PaginatedStudentListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedStudentListList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StudentListFromJSON)),
    };
}

export function PaginatedStudentListListToJSON(value?: PaginatedStudentListList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StudentListToJSON)),
    };
}

