/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ItemLoanLog,
    ItemLoanLogFromJSON,
    ItemLoanLogFromJSONTyped,
    ItemLoanLogToJSON,
} from './ItemLoanLog';

/**
 * 
 * @export
 * @interface PaginatedItemLoanLogList
 */
export interface PaginatedItemLoanLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedItemLoanLogList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedItemLoanLogList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedItemLoanLogList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ItemLoanLog>}
     * @memberof PaginatedItemLoanLogList
     */
    results?: Array<ItemLoanLog>;
}

export function PaginatedItemLoanLogListFromJSON(json: any): PaginatedItemLoanLogList {
    return PaginatedItemLoanLogListFromJSONTyped(json, false);
}

export function PaginatedItemLoanLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedItemLoanLogList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ItemLoanLogFromJSON)),
    };
}

export function PaginatedItemLoanLogListToJSON(value?: PaginatedItemLoanLogList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ItemLoanLogToJSON)),
    };
}

