/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LessonGetAttendance,
    LessonGetAttendanceFromJSON,
    LessonGetAttendanceFromJSONTyped,
    LessonGetAttendanceToJSON,
} from './LessonGetAttendance';

/**
 * 
 * @export
 * @interface PaginatedLessonGetAttendanceList
 */
export interface PaginatedLessonGetAttendanceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLessonGetAttendanceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLessonGetAttendanceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLessonGetAttendanceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LessonGetAttendance>}
     * @memberof PaginatedLessonGetAttendanceList
     */
    results?: Array<LessonGetAttendance>;
}

export function PaginatedLessonGetAttendanceListFromJSON(json: any): PaginatedLessonGetAttendanceList {
    return PaginatedLessonGetAttendanceListFromJSONTyped(json, false);
}

export function PaginatedLessonGetAttendanceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLessonGetAttendanceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LessonGetAttendanceFromJSON)),
    };
}

export function PaginatedLessonGetAttendanceListToJSON(value?: PaginatedLessonGetAttendanceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LessonGetAttendanceToJSON)),
    };
}

