/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LongTermAbsence,
    LongTermAbsenceFromJSON,
    LongTermAbsenceFromJSONTyped,
    LongTermAbsenceToJSON,
} from './LongTermAbsence';

/**
 * 
 * @export
 * @interface PaginatedLongTermAbsenceList
 */
export interface PaginatedLongTermAbsenceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLongTermAbsenceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLongTermAbsenceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLongTermAbsenceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LongTermAbsence>}
     * @memberof PaginatedLongTermAbsenceList
     */
    results?: Array<LongTermAbsence>;
}

export function PaginatedLongTermAbsenceListFromJSON(json: any): PaginatedLongTermAbsenceList {
    return PaginatedLongTermAbsenceListFromJSONTyped(json, false);
}

export function PaginatedLongTermAbsenceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLongTermAbsenceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LongTermAbsenceFromJSON)),
    };
}

export function PaginatedLongTermAbsenceListToJSON(value?: PaginatedLongTermAbsenceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LongTermAbsenceToJSON)),
    };
}

