/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Class,
    ClassFromJSON,
    ClassFromJSONTyped,
    ClassToJSON,
} from './Class';

/**
 * 
 * @export
 * @interface PaginatedClassList
 */
export interface PaginatedClassList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedClassList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClassList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedClassList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Class>}
     * @memberof PaginatedClassList
     */
    results?: Array<Class>;
}

export function PaginatedClassListFromJSON(json: any): PaginatedClassList {
    return PaginatedClassListFromJSONTyped(json, false);
}

export function PaginatedClassListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedClassList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ClassFromJSON)),
    };
}

export function PaginatedClassListToJSON(value?: PaginatedClassList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ClassToJSON)),
    };
}

