/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClassRequest,
    ClassRequestFromJSON,
    ClassRequestFromJSONTyped,
    ClassRequestToJSON,
} from './ClassRequest';

/**
 * 
 * @export
 * @interface PatchedLessonRequest
 */
export interface PatchedLessonRequest {
    /**
     * 
     * @type {Date}
     * @memberof PatchedLessonRequest
     */
    startDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLessonRequest
     */
    endDateTime?: Date;
    /**
     * 
     * @type {ClassRequest}
     * @memberof PatchedLessonRequest
     */
    classFk?: ClassRequest;
    /**
     * 
     * @type {number}
     * @memberof PatchedLessonRequest
     */
    subjectLevel?: number;
}

export function PatchedLessonRequestFromJSON(json: any): PatchedLessonRequest {
    return PatchedLessonRequestFromJSONTyped(json, false);
}

export function PatchedLessonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLessonRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startDateTime': !exists(json, 'startDateTime') ? undefined : (new Date(json['startDateTime'])),
        'endDateTime': !exists(json, 'endDateTime') ? undefined : (new Date(json['endDateTime'])),
        'classFk': !exists(json, 'class_fk') ? undefined : ClassRequestFromJSON(json['class_fk']),
        'subjectLevel': !exists(json, 'subject_level') ? undefined : json['subject_level'],
    };
}

export function PatchedLessonRequestToJSON(value?: PatchedLessonRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startDateTime': value.startDateTime === undefined ? undefined : (value.startDateTime.toISOString()),
        'endDateTime': value.endDateTime === undefined ? undefined : (value.endDateTime.toISOString()),
        'class_fk': ClassRequestToJSON(value.classFk),
        'subject_level': value.subjectLevel,
    };
}

