/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressRequest,
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
} from './AddressRequest';
import {
    GradeEnum,
    GradeEnumFromJSON,
    GradeEnumFromJSONTyped,
    GradeEnumToJSON,
} from './GradeEnum';

/**
 * 
 * @export
 * @interface PatchedStudentRequest
 */
export interface PatchedStudentRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedStudentRequest
     */
    kSisId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    lastName?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedStudentRequest
     */
    dateOfBirth?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedStudentRequest
     */
    joinDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof PatchedStudentRequest
     */
    leaveDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    phoneNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    school?: string;
    /**
     * 
     * @type {GradeEnum}
     * @memberof PatchedStudentRequest
     */
    grade?: GradeEnum;
    /**
     * 
     * @type {AddressRequest}
     * @memberof PatchedStudentRequest
     */
    address?: AddressRequest;
    /**
     * 
     * @type {string}
     * @memberof PatchedStudentRequest
     */
    email?: string;
}

export function PatchedStudentRequestFromJSON(json: any): PatchedStudentRequest {
    return PatchedStudentRequestFromJSONTyped(json, false);
}

export function PatchedStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedStudentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kSisId': !exists(json, 'k_sis_id') ? undefined : json['k_sis_id'],
        'firstName': !exists(json, 'first_name') ? undefined : json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': !exists(json, 'last_name') ? undefined : json['last_name'],
        'dateOfBirth': !exists(json, 'date_of_birth') ? undefined : (new Date(json['date_of_birth'])),
        'joinDate': !exists(json, 'join_date') ? undefined : (json['join_date'] === null ? null : new Date(json['join_date'])),
        'leaveDate': !exists(json, 'leave_date') ? undefined : (json['leave_date'] === null ? null : new Date(json['leave_date'])),
        'phoneNumber': !exists(json, 'phone_number') ? undefined : json['phone_number'],
        'school': !exists(json, 'school') ? undefined : json['school'],
        'grade': !exists(json, 'grade') ? undefined : GradeEnumFromJSON(json['grade']),
        'address': !exists(json, 'address') ? undefined : AddressRequestFromJSON(json['address']),
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function PatchedStudentRequestToJSON(value?: PatchedStudentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_sis_id': value.kSisId,
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'date_of_birth': value.dateOfBirth === undefined ? undefined : (value.dateOfBirth.toISOString().substr(0,10)),
        'join_date': value.joinDate === undefined ? undefined : (value.joinDate === null ? null : value.joinDate.toISOString().substr(0,10)),
        'leave_date': value.leaveDate === undefined ? undefined : (value.leaveDate === null ? null : value.leaveDate.toISOString().substr(0,10)),
        'phone_number': value.phoneNumber,
        'school': value.school,
        'grade': GradeEnumToJSON(value.grade),
        'address': AddressRequestToJSON(value.address),
        'email': value.email,
    };
}

