/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedItemLoanRequest
 */
export interface PatchedItemLoanRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedItemLoanRequest
     */
    itemId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedItemLoanRequest
     */
    studentId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedItemLoanRequest
     */
    quantity?: number;
}

export function PatchedItemLoanRequestFromJSON(json: any): PatchedItemLoanRequest {
    return PatchedItemLoanRequestFromJSONTyped(json, false);
}

export function PatchedItemLoanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedItemLoanRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': !exists(json, 'item_id') ? undefined : json['item_id'],
        'studentId': !exists(json, 'student_id') ? undefined : json['student_id'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function PatchedItemLoanRequestToJSON(value?: PatchedItemLoanRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'student_id': value.studentId,
        'quantity': value.quantity,
    };
}

