/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StaffCreate
 */
export interface StaffCreate {
    /**
     * 
     * @type {string}
     * @memberof StaffCreate
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StaffCreate
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof StaffCreate
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof StaffCreate
     */
    jobTitle: string;
    /**
     * 
     * @type {string}
     * @memberof StaffCreate
     */
    username: string;
}

export function StaffCreateFromJSON(json: any): StaffCreate {
    return StaffCreateFromJSONTyped(json, false);
}

export function StaffCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StaffCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'jobTitle': json['job_title'],
        'username': json['username'],
    };
}

export function StaffCreateToJSON(value?: StaffCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'job_title': value.jobTitle,
        'username': value.username,
    };
}

