/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Staff
 */
export interface Staff {
    /**
     * 
     * @type {number}
     * @memberof Staff
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof Staff
     */
    jobTitle: string;
    /**
     * 
     * @type {Date}
     * @memberof Staff
     */
    joinDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Staff
     */
    leaveDate?: Date | null;
}

export function StaffFromJSON(json: any): Staff {
    return StaffFromJSONTyped(json, false);
}

export function StaffFromJSONTyped(json: any, ignoreDiscriminator: boolean): Staff {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'jobTitle': json['job_title'],
        'joinDate': !exists(json, 'join_date') ? undefined : (json['join_date'] === null ? null : new Date(json['join_date'])),
        'leaveDate': !exists(json, 'leave_date') ? undefined : (json['leave_date'] === null ? null : new Date(json['leave_date'])),
    };
}

export function StaffToJSON(value?: Staff | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'job_title': value.jobTitle,
        'join_date': value.joinDate === undefined ? undefined : (value.joinDate === null ? null : value.joinDate.toISOString().substr(0,10)),
        'leave_date': value.leaveDate === undefined ? undefined : (value.leaveDate === null ? null : value.leaveDate.toISOString().substr(0,10)),
    };
}

