/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for adding or removing contacts from a student.
 * @export
 * @interface StudentAddRemoveContactsRequest
 */
export interface StudentAddRemoveContactsRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof StudentAddRemoveContactsRequest
     */
    ids: Array<number>;
}

export function StudentAddRemoveContactsRequestFromJSON(json: any): StudentAddRemoveContactsRequest {
    return StudentAddRemoveContactsRequestFromJSONTyped(json, false);
}

export function StudentAddRemoveContactsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentAddRemoveContactsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

export function StudentAddRemoveContactsRequestToJSON(value?: StudentAddRemoveContactsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ids': value.ids,
    };
}

