/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LessonView,
    LessonViewFromJSON,
    LessonViewFromJSONTyped,
    LessonViewToJSON,
} from './LessonView';
import {
    StatusEnum,
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
} from './StatusEnum';

/**
 * Serializer for retrieving student attendance records.
 * @export
 * @interface StudentGetAttendance
 */
export interface StudentGetAttendance {
    /**
     * 
     * @type {LessonView}
     * @memberof StudentGetAttendance
     */
    lesson: LessonView;
    /**
     * 
     * @type {StatusEnum}
     * @memberof StudentGetAttendance
     */
    status: StatusEnum;
}

export function StudentGetAttendanceFromJSON(json: any): StudentGetAttendance {
    return StudentGetAttendanceFromJSONTyped(json, false);
}

export function StudentGetAttendanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentGetAttendance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'lesson': LessonViewFromJSON(json['lesson']),
        'status': StatusEnumFromJSON(json['status']),
    };
}

export function StudentGetAttendanceToJSON(value?: StudentGetAttendance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lesson': LessonViewToJSON(value.lesson),
        'status': StatusEnumToJSON(value.status),
    };
}

