/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for removing contacts from a student.
 * @export
 * @interface StudentRemoveContactsRequest
 */
export interface StudentRemoveContactsRequest {
    /**
     * 
     * @type {number}
     * @memberof StudentRemoveContactsRequest
     */
    contactId: number;
}

export function StudentRemoveContactsRequestFromJSON(json: any): StudentRemoveContactsRequest {
    return StudentRemoveContactsRequestFromJSONTyped(json, false);
}

export function StudentRemoveContactsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentRemoveContactsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contactId': json['contact_id'],
    };
}

export function StudentRemoveContactsRequestToJSON(value?: StudentRemoveContactsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contact_id': value.contactId,
    };
}

