/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for students which only includes their name and IDs.
 * @export
 * @interface StudentListRequest
 */
export interface StudentListRequest {
    /**
     * 
     * @type {number}
     * @memberof StudentListRequest
     */
    kSisId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StudentListRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StudentListRequest
     */
    lastName: string;
}

export function StudentListRequestFromJSON(json: any): StudentListRequest {
    return StudentListRequestFromJSONTyped(json, false);
}

export function StudentListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentListRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kSisId': !exists(json, 'k_sis_id') ? undefined : json['k_sis_id'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
    };
}

export function StudentListRequestToJSON(value?: StudentListRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_sis_id': value.kSisId,
        'first_name': value.firstName,
        'last_name': value.lastName,
    };
}

