/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for adding contacts to a student.
 * @export
 * @interface StudentAddContactsRequest
 */
export interface StudentAddContactsRequest {
    /**
     * 
     * @type {number}
     * @memberof StudentAddContactsRequest
     */
    contactId: number;
    /**
     * 
     * @type {string}
     * @memberof StudentAddContactsRequest
     */
    relationship: string;
}

export function StudentAddContactsRequestFromJSON(json: any): StudentAddContactsRequest {
    return StudentAddContactsRequestFromJSONTyped(json, false);
}

export function StudentAddContactsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentAddContactsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contactId': json['contact_id'],
        'relationship': json['relationship'],
    };
}

export function StudentAddContactsRequestToJSON(value?: StudentAddContactsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contact_id': value.contactId,
        'relationship': value.relationship,
    };
}

