/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubjectGetLevel
 */
export interface SubjectGetLevel {
    /**
     * 
     * @type {number}
     * @memberof SubjectGetLevel
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SubjectGetLevel
     */
    name: string;
}

export function SubjectGetLevelFromJSON(json: any): SubjectGetLevel {
    return SubjectGetLevelFromJSONTyped(json, false);
}

export function SubjectGetLevelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectGetLevel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function SubjectGetLevelToJSON(value?: SubjectGetLevel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

