/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Subject,
    SubjectFromJSON,
    SubjectFromJSONTyped,
    SubjectToJSON,
} from './Subject';
import {
    SubjectGetLevel,
    SubjectGetLevelFromJSON,
    SubjectGetLevelFromJSONTyped,
    SubjectGetLevelToJSON,
} from './SubjectGetLevel';

/**
 * 
 * @export
 * @interface WorksheetView
 */
export interface WorksheetView {
    /**
     * 
     * @type {number}
     * @memberof WorksheetView
     */
    readonly id: number;
    /**
     * 
     * @type {Subject}
     * @memberof WorksheetView
     */
    readonly subject: Subject | null;
    /**
     * 
     * @type {SubjectGetLevel}
     * @memberof WorksheetView
     */
    subjectLevel: SubjectGetLevel;
    /**
     * 
     * @type {string}
     * @memberof WorksheetView
     */
    set: string;
    /**
     * 
     * @type {number}
     * @memberof WorksheetView
     */
    quantity?: number;
}

export function WorksheetViewFromJSON(json: any): WorksheetView {
    return WorksheetViewFromJSONTyped(json, false);
}

export function WorksheetViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorksheetView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'subject': SubjectFromJSON(json['subject']),
        'subjectLevel': SubjectGetLevelFromJSON(json['subject_level']),
        'set': json['set'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function WorksheetViewToJSON(value?: WorksheetView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject_level': SubjectGetLevelToJSON(value.subjectLevel),
        'set': value.set,
        'quantity': value.quantity,
    };
}

