/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WorksheetEdit
 */
export interface WorksheetEdit {
    /**
     * 
     * @type {number}
     * @memberof WorksheetEdit
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof WorksheetEdit
     */
    subjectLevel?: number | null;
    /**
     * 
     * @type {string}
     * @memberof WorksheetEdit
     */
    set: string;
    /**
     * 
     * @type {number}
     * @memberof WorksheetEdit
     */
    quantity?: number;
}

export function WorksheetEditFromJSON(json: any): WorksheetEdit {
    return WorksheetEditFromJSONTyped(json, false);
}

export function WorksheetEditFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorksheetEdit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'subjectLevel': !exists(json, 'subject_level') ? undefined : json['subject_level'],
        'set': json['set'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function WorksheetEditToJSON(value?: WorksheetEdit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject_level': value.subjectLevel,
        'set': value.set,
        'quantity': value.quantity,
    };
}

