<script>
  import { push, pop } from "svelte-spa-router";
  import dayjs from "dayjs";
  import { createEventDispatcher } from "svelte";
  import { fade } from "svelte/transition";
  import { Button, FormGroup, Input, Label, Spinner } from "sveltestrap";
  import { Modals, closeModal, openModal } from "svelte-modals";

  import API_CONFIG from "../../api";
  import { ImportApi, FileTypeEnum } from "kumon_app_backend_api";
  import InfoModal from "../../modals/InfoModal.svelte";
  import { Imports } from "../../utils";

  /**
   * The import API client instance we're using.
   * @type {ImportApi}
   */
  export let importApi = new ImportApi(API_CONFIG);

  /**
   * Svelte event dispatcher instance.
   */
  const dispatch = createEventDispatcher();

  /**
   * Internal array holding the files we are attempting to import.
   */
  let selectedFiles = [];

  /**
   * The name of the import we are creating.
   */
  let importName = "";

  /**
   * Whether an import is currently happening.
   */
  let loading = false;


  /**
   * Handler for import form submission.
   */
  async function handleImport() {
    try {
      loading = true;

      // Send a backend import request
      await importApi.importFirstImportCreate({
        name: "Database Initialisation Import",
        file: selectedFiles[0],
        type: FileTypeEnum.Dumps,
      });

      loading = false;

      // Open a modal to inform the user of successful importing
      openModal(InfoModal, {
        title: "Import Data",
        message: "Successfully imported data!",
      });
      push("/");
    } catch (e) {
      loading = false;

      // Open a modal to inform the user that the import was unsuccessful
      openModal(InfoModal, {
        title: "Import Data",
        message: "Could not import data!",
      });
    }
  }

  function back() {
    pop();
  }
</script>

<main>
  <div class="title">
    <h1>Kumon Management System</h1>

    <p>
      This setup approach uses a .kumon export file generated by the Kumon
      Management System Application. Once imported, this application will be in
      the same state as that from which the import file comes from. You will
      then be taken to the Login Page.
    </p>
    <Button color="secondary" on:click={back}>Back</Button>
  </div>

  <div class="body">
    <p>
      Please upload the .kumon export file below and press "Import" to start the
      process.
    </p>
    <br />
    <form
      class="body"
      on:submit|preventDefault={async () => await handleImport()}
    >
      <FormGroup>
        <Label for="importFile">Choose a file:</Label>
        <Input
          id="importFile"
          type="file"
          accept=".kumon"
          required
          bind:files={selectedFiles}
        />
      </FormGroup>

      <Button color="primary" type="submit" disabled={loading}>Import</Button>
      {#if loading}
        <Spinner color="primary"/>
      {/if}
    </form>
  </div>
</main>

<style>
  main {
    width: 100%;
    max-height: 100%;
    max-width: 40%;
    margin-left: auto;
    margin-right: auto;
  }

  .title {
    text-align: center;
    margin-top: 5%;
  }

  .body {
    margin-top: 20%;
    margin-bottom: 20%;
    margin-left: auto;
    margin-right: auto;
    max-width: 60%;
    min-width: 450px;
    text-align: left;
  }
</style>
