/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating a new account.
 * @export
 * @interface AddAccountRequest
 */
export interface AddAccountRequest {
    /**
     * 
     * @type {string}
     * @memberof AddAccountRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof AddAccountRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof AddAccountRequest
     */
    confirmPassword: string;
}

export function AddAccountRequestFromJSON(json: any): AddAccountRequest {
    return AddAccountRequestFromJSONTyped(json, false);
}

export function AddAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddAccountRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'confirmPassword': json['confirm_password'],
    };
}

export function AddAccountRequestToJSON(value?: AddAccountRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'password': value.password,
        'confirm_password': value.confirmPassword,
    };
}

