/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StatusEnum,
    StatusEnumFromJSON,
    StatusEnumFromJSONTyped,
    StatusEnumToJSON,
} from './StatusEnum';

/**
 * 
 * @export
 * @interface Attendance
 */
export interface Attendance {
    /**
     * 
     * @type {number}
     * @memberof Attendance
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof Attendance
     */
    lesson: number;
    /**
     * 
     * @type {number}
     * @memberof Attendance
     */
    student: number;
    /**
     * 
     * @type {StatusEnum}
     * @memberof Attendance
     */
    status: StatusEnum;
}

export function AttendanceFromJSON(json: any): Attendance {
    return AttendanceFromJSONTyped(json, false);
}

export function AttendanceFromJSONTyped(json: any, ignoreDiscriminator: boolean): Attendance {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'lesson': json['lesson'],
        'student': json['student'],
        'status': StatusEnumFromJSON(json['status']),
    };
}

export function AttendanceToJSON(value?: Attendance | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'lesson': value.lesson,
        'student': value.student,
        'status': StatusEnumToJSON(value.status),
    };
}

