/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BulkItem
 */
export interface BulkItem {
    /**
     * 
     * @type {number}
     * @memberof BulkItem
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof BulkItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof BulkItem
     */
    quantity?: number;
}

export function BulkItemFromJSON(json: any): BulkItem {
    return BulkItemFromJSONTyped(json, false);
}

export function BulkItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function BulkItemToJSON(value?: BulkItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'quantity': value.quantity,
    };
}

