/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Address,
    AddressFromJSON,
    AddressFromJSONTyped,
    AddressToJSON,
} from './Address';

/**
 * 
 * @export
 * @interface CenterDetails
 */
export interface CenterDetails {
    /**
     * 
     * @type {string}
     * @memberof CenterDetails
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof CenterDetails
     */
    phoneNumber: string;
    /**
     * 
     * @type {Address}
     * @memberof CenterDetails
     */
    address: Address;
}

export function CenterDetailsFromJSON(json: any): CenterDetails {
    return CenterDetailsFromJSONTyped(json, false);
}

export function CenterDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CenterDetails {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'phoneNumber': json['phone_number'],
        'address': AddressFromJSON(json['address']),
    };
}

export function CenterDetailsToJSON(value?: CenterDetails | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'phone_number': value.phoneNumber,
        'address': AddressToJSON(value.address),
    };
}

