/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for contact details which only includes ID and name.
 * @export
 * @interface ContactList
 */
export interface ContactList {
    /**
     * 
     * @type {number}
     * @memberof ContactList
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof ContactList
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ContactList
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactList
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ContactList
     */
    email: string;
}

export function ContactListFromJSON(json: any): ContactList {
    return ContactListFromJSONTyped(json, false);
}

export function ContactListFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'email': json['email'],
    };
}

export function ContactListToJSON(value?: ContactList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'email': value.email,
    };
}

