/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressRequest,
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
} from './AddressRequest';

/**
 * Serializer for contact details.
 * @export
 * @interface ContactRequest
 */
export interface ContactRequest {
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    phoneHome?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    phoneBusiness?: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    phoneMobile: string;
    /**
     * 
     * @type {string}
     * @memberof ContactRequest
     */
    email: string;
    /**
     * 
     * @type {AddressRequest}
     * @memberof ContactRequest
     */
    address: AddressRequest;
}

export function ContactRequestFromJSON(json: any): ContactRequest {
    return ContactRequestFromJSONTyped(json, false);
}

export function ContactRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContactRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'phoneHome': !exists(json, 'phone_home') ? undefined : json['phone_home'],
        'phoneBusiness': !exists(json, 'phone_business') ? undefined : json['phone_business'],
        'phoneMobile': json['phone_mobile'],
        'email': json['email'],
        'address': AddressRequestFromJSON(json['address']),
    };
}

export function ContactRequestToJSON(value?: ContactRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'phone_home': value.phoneHome,
        'phone_business': value.phoneBusiness,
        'phone_mobile': value.phoneMobile,
        'email': value.email,
        'address': AddressRequestToJSON(value.address),
    };
}

