/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemLoan
 */
export interface ItemLoan {
    /**
     * 
     * @type {number}
     * @memberof ItemLoan
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoan
     */
    itemId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoan
     */
    studentId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoan
     */
    quantity: number;
    /**
     * 
     * @type {Date}
     * @memberof ItemLoan
     */
    readonly createdAt: Date;
}

export function ItemLoanFromJSON(json: any): ItemLoan {
    return ItemLoanFromJSONTyped(json, false);
}

export function ItemLoanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemLoan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'itemId': json['item_id'],
        'studentId': json['student_id'],
        'quantity': json['quantity'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function ItemLoanToJSON(value?: ItemLoan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'student_id': value.studentId,
        'quantity': value.quantity,
    };
}

