/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ItemLoanRequest
 */
export interface ItemLoanRequest {
    /**
     * 
     * @type {number}
     * @memberof ItemLoanRequest
     */
    itemId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanRequest
     */
    studentId: number;
    /**
     * 
     * @type {number}
     * @memberof ItemLoanRequest
     */
    quantity: number;
}

export function ItemLoanRequestFromJSON(json: any): ItemLoanRequest {
    return ItemLoanRequestFromJSONTyped(json, false);
}

export function ItemLoanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItemLoanRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'studentId': json['student_id'],
        'quantity': json['quantity'],
    };
}

export function ItemLoanRequestToJSON(value?: ItemLoanRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'item_id': value.itemId,
        'student_id': value.studentId,
        'quantity': value.quantity,
    };
}

