/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LendableItemEditRequest
 */
export interface LendableItemEditRequest {
    /**
     * 
     * @type {string}
     * @memberof LendableItemEditRequest
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof LendableItemEditRequest
     */
    quantityAvailable?: number;
}

export function LendableItemEditRequestFromJSON(json: any): LendableItemEditRequest {
    return LendableItemEditRequestFromJSONTyped(json, false);
}

export function LendableItemEditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LendableItemEditRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'quantityAvailable': !exists(json, 'quantity_available') ? undefined : json['quantity_available'],
    };
}

export function LendableItemEditRequestToJSON(value?: LendableItemEditRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'quantity_available': value.quantityAvailable,
    };
}

