/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LessonEdit
 */
export interface LessonEdit {
    /**
     * 
     * @type {number}
     * @memberof LessonEdit
     */
    readonly id: number;
    /**
     * 
     * @type {Date}
     * @memberof LessonEdit
     */
    startDatetime: Date;
    /**
     * 
     * @type {Date}
     * @memberof LessonEdit
     */
    endDatetime: Date;
    /**
     * 
     * @type {number}
     * @memberof LessonEdit
     */
    classFk: number;
    /**
     * 
     * @type {number}
     * @memberof LessonEdit
     */
    subjectLevel: number;
}

export function LessonEditFromJSON(json: any): LessonEdit {
    return LessonEditFromJSONTyped(json, false);
}

export function LessonEditFromJSONTyped(json: any, ignoreDiscriminator: boolean): LessonEdit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'startDatetime': (new Date(json['start_datetime'])),
        'endDatetime': (new Date(json['end_datetime'])),
        'classFk': json['class_fk'],
        'subjectLevel': json['subject_level'],
    };
}

export function LessonEditToJSON(value?: LessonEdit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start_datetime': (value.startDatetime.toISOString()),
        'end_datetime': (value.endDatetime.toISOString()),
        'class_fk': value.classFk,
        'subject_level': value.subjectLevel,
    };
}

