/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ClassRequest,
    ClassRequestFromJSON,
    ClassRequestFromJSONTyped,
    ClassRequestToJSON,
} from './ClassRequest';

/**
 * 
 * @export
 * @interface LessonRequest
 */
export interface LessonRequest {
    /**
     * 
     * @type {Date}
     * @memberof LessonRequest
     */
    startDateTime: Date;
    /**
     * 
     * @type {Date}
     * @memberof LessonRequest
     */
    endDateTime: Date;
    /**
     * 
     * @type {ClassRequest}
     * @memberof LessonRequest
     */
    classFk: ClassRequest;
    /**
     * 
     * @type {number}
     * @memberof LessonRequest
     */
    subjectLevel: number;
}

export function LessonRequestFromJSON(json: any): LessonRequest {
    return LessonRequestFromJSONTyped(json, false);
}

export function LessonRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LessonRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'startDateTime': (new Date(json['startDateTime'])),
        'endDateTime': (new Date(json['endDateTime'])),
        'classFk': ClassRequestFromJSON(json['class_fk']),
        'subjectLevel': json['subject_level'],
    };
}

export function LessonRequestToJSON(value?: LessonRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'startDateTime': (value.startDateTime.toISOString()),
        'endDateTime': (value.endDateTime.toISOString()),
        'class_fk': ClassRequestToJSON(value.classFk),
        'subject_level': value.subjectLevel,
    };
}

