/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LongTermAbsenceEdit
 */
export interface LongTermAbsenceEdit {
    /**
     * 
     * @type {number}
     * @memberof LongTermAbsenceEdit
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof LongTermAbsenceEdit
     */
    student: number;
    /**
     * 
     * @type {Date}
     * @memberof LongTermAbsenceEdit
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof LongTermAbsenceEdit
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof LongTermAbsenceEdit
     */
    reason: string;
}

export function LongTermAbsenceEditFromJSON(json: any): LongTermAbsenceEdit {
    return LongTermAbsenceEditFromJSONTyped(json, false);
}

export function LongTermAbsenceEditFromJSONTyped(json: any, ignoreDiscriminator: boolean): LongTermAbsenceEdit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'student': json['student'],
        'startDate': (new Date(json['start_date'])),
        'endDate': (new Date(json['end_date'])),
        'reason': json['reason'],
    };
}

export function LongTermAbsenceEditToJSON(value?: LongTermAbsenceEdit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student': value.student,
        'start_date': (value.startDate.toISOString().substr(0,10)),
        'end_date': (value.endDate.toISOString().substr(0,10)),
        'reason': value.reason,
    };
}

