/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudentList,
    StudentListFromJSON,
    StudentListFromJSONTyped,
    StudentListToJSON,
} from './StudentList';

/**
 * 
 * @export
 * @interface LongTermAbsence
 */
export interface LongTermAbsence {
    /**
     * 
     * @type {number}
     * @memberof LongTermAbsence
     */
    readonly id: number;
    /**
     * 
     * @type {StudentList}
     * @memberof LongTermAbsence
     */
    student: StudentList;
    /**
     * 
     * @type {Date}
     * @memberof LongTermAbsence
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof LongTermAbsence
     */
    endDate: Date;
    /**
     * 
     * @type {string}
     * @memberof LongTermAbsence
     */
    reason: string;
}

export function LongTermAbsenceFromJSON(json: any): LongTermAbsence {
    return LongTermAbsenceFromJSONTyped(json, false);
}

export function LongTermAbsenceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LongTermAbsence {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'student': StudentListFromJSON(json['student']),
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'reason': json['reason'],
    };
}

export function LongTermAbsenceToJSON(value?: LongTermAbsence | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student': StudentListToJSON(value.student),
        'startDate': (value.startDate.toISOString().substr(0,10)),
        'endDate': (value.endDate.toISOString().substr(0,10)),
        'reason': value.reason,
    };
}

