/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedFileList
 */
export interface PaginatedFileList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedFileList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedFileList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<any>}
     * @memberof PaginatedFileList
     */
    results?: Array<any>;
}

export function PaginatedFileListFromJSON(json: any): PaginatedFileList {
    return PaginatedFileListFromJSONTyped(json, false);
}

export function PaginatedFileListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedFileList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : json['results'],
    };
}

export function PaginatedFileListToJSON(value?: PaginatedFileList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results,
    };
}

