/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContactList,
    ContactListFromJSON,
    ContactListFromJSONTyped,
    ContactListToJSON,
} from './ContactList';

/**
 * 
 * @export
 * @interface PaginatedContactListList
 */
export interface PaginatedContactListList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedContactListList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedContactListList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedContactListList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ContactList>}
     * @memberof PaginatedContactListList
     */
    results?: Array<ContactList>;
}

export function PaginatedContactListListFromJSON(json: any): PaginatedContactListList {
    return PaginatedContactListListFromJSONTyped(json, false);
}

export function PaginatedContactListListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedContactListList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ContactListFromJSON)),
    };
}

export function PaginatedContactListListToJSON(value?: PaginatedContactListList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ContactListToJSON)),
    };
}

