/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LongTermAbsenceView,
    LongTermAbsenceViewFromJSON,
    LongTermAbsenceViewFromJSONTyped,
    LongTermAbsenceViewToJSON,
} from './LongTermAbsenceView';

/**
 * 
 * @export
 * @interface PaginatedLongTermAbsenceViewList
 */
export interface PaginatedLongTermAbsenceViewList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLongTermAbsenceViewList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLongTermAbsenceViewList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLongTermAbsenceViewList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LongTermAbsenceView>}
     * @memberof PaginatedLongTermAbsenceViewList
     */
    results?: Array<LongTermAbsenceView>;
}

export function PaginatedLongTermAbsenceViewListFromJSON(json: any): PaginatedLongTermAbsenceViewList {
    return PaginatedLongTermAbsenceViewListFromJSONTyped(json, false);
}

export function PaginatedLongTermAbsenceViewListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLongTermAbsenceViewList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LongTermAbsenceViewFromJSON)),
    };
}

export function PaginatedLongTermAbsenceViewListToJSON(value?: PaginatedLongTermAbsenceViewList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LongTermAbsenceViewToJSON)),
    };
}

