/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BulkItemLog,
    BulkItemLogFromJSON,
    BulkItemLogFromJSONTyped,
    BulkItemLogToJSON,
} from './BulkItemLog';

/**
 * 
 * @export
 * @interface PaginatedBulkItemLogList
 */
export interface PaginatedBulkItemLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBulkItemLogList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBulkItemLogList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBulkItemLogList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BulkItemLog>}
     * @memberof PaginatedBulkItemLogList
     */
    results?: Array<BulkItemLog>;
}

export function PaginatedBulkItemLogListFromJSON(json: any): PaginatedBulkItemLogList {
    return PaginatedBulkItemLogListFromJSONTyped(json, false);
}

export function PaginatedBulkItemLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBulkItemLogList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(BulkItemLogFromJSON)),
    };
}

export function PaginatedBulkItemLogListToJSON(value?: PaginatedBulkItemLogList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(BulkItemLogToJSON)),
    };
}

