/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ItemLoan,
    ItemLoanFromJSON,
    ItemLoanFromJSONTyped,
    ItemLoanToJSON,
} from './ItemLoan';

/**
 * 
 * @export
 * @interface PaginatedItemLoanList
 */
export interface PaginatedItemLoanList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedItemLoanList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedItemLoanList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedItemLoanList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<ItemLoan>}
     * @memberof PaginatedItemLoanList
     */
    results?: Array<ItemLoan>;
}

export function PaginatedItemLoanListFromJSON(json: any): PaginatedItemLoanList {
    return PaginatedItemLoanListFromJSONTyped(json, false);
}

export function PaginatedItemLoanListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedItemLoanList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(ItemLoanFromJSON)),
    };
}

export function PaginatedItemLoanListToJSON(value?: PaginatedItemLoanList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(ItemLoanToJSON)),
    };
}

