/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LessonView,
    LessonViewFromJSON,
    LessonViewFromJSONTyped,
    LessonViewToJSON,
} from './LessonView';

/**
 * 
 * @export
 * @interface PaginatedLessonViewList
 */
export interface PaginatedLessonViewList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLessonViewList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLessonViewList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLessonViewList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LessonView>}
     * @memberof PaginatedLessonViewList
     */
    results?: Array<LessonView>;
}

export function PaginatedLessonViewListFromJSON(json: any): PaginatedLessonViewList {
    return PaginatedLessonViewListFromJSONTyped(json, false);
}

export function PaginatedLessonViewListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLessonViewList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LessonViewFromJSON)),
    };
}

export function PaginatedLessonViewListToJSON(value?: PaginatedLessonViewList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LessonViewToJSON)),
    };
}

