/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LendableItem,
    LendableItemFromJSON,
    LendableItemFromJSONTyped,
    LendableItemToJSON,
} from './LendableItem';

/**
 * 
 * @export
 * @interface PaginatedLendableItemList
 */
export interface PaginatedLendableItemList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLendableItemList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLendableItemList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLendableItemList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<LendableItem>}
     * @memberof PaginatedLendableItemList
     */
    results?: Array<LendableItem>;
}

export function PaginatedLendableItemListFromJSON(json: any): PaginatedLendableItemList {
    return PaginatedLendableItemListFromJSONTyped(json, false);
}

export function PaginatedLendableItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLendableItemList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(LendableItemFromJSON)),
    };
}

export function PaginatedLendableItemListToJSON(value?: PaginatedLendableItemList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(LendableItemToJSON)),
    };
}

