/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    StudentGetAttendance,
    StudentGetAttendanceFromJSON,
    StudentGetAttendanceFromJSONTyped,
    StudentGetAttendanceToJSON,
} from './StudentGetAttendance';

/**
 * 
 * @export
 * @interface PaginatedStudentGetAttendanceList
 */
export interface PaginatedStudentGetAttendanceList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedStudentGetAttendanceList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStudentGetAttendanceList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStudentGetAttendanceList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<StudentGetAttendance>}
     * @memberof PaginatedStudentGetAttendanceList
     */
    results?: Array<StudentGetAttendance>;
}

export function PaginatedStudentGetAttendanceListFromJSON(json: any): PaginatedStudentGetAttendanceList {
    return PaginatedStudentGetAttendanceListFromJSONTyped(json, false);
}

export function PaginatedStudentGetAttendanceListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedStudentGetAttendanceList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(StudentGetAttendanceFromJSON)),
    };
}

export function PaginatedStudentGetAttendanceListToJSON(value?: PaginatedStudentGetAttendanceList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(StudentGetAttendanceToJSON)),
    };
}

