/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBulkItemRequest
 */
export interface PatchedBulkItemRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedBulkItemRequest
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedBulkItemRequest
     */
    quantity?: number;
}

export function PatchedBulkItemRequestFromJSON(json: any): PatchedBulkItemRequest {
    return PatchedBulkItemRequestFromJSONTyped(json, false);
}

export function PatchedBulkItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBulkItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function PatchedBulkItemRequestToJSON(value?: PatchedBulkItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'quantity': value.quantity,
    };
}

