/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedClassRequest
 */
export interface PatchedClassRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedClassRequest
     */
    name?: string;
}

export function PatchedClassRequestFromJSON(json: any): PatchedClassRequest {
    return PatchedClassRequestFromJSONTyped(json, false);
}

export function PatchedClassRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedClassRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedClassRequestToJSON(value?: PatchedClassRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

