/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedLongTermAbsenceEditRequest
 */
export interface PatchedLongTermAbsenceEditRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedLongTermAbsenceEditRequest
     */
    student?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLongTermAbsenceEditRequest
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedLongTermAbsenceEditRequest
     */
    endDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedLongTermAbsenceEditRequest
     */
    reason?: string;
}

export function PatchedLongTermAbsenceEditRequestFromJSON(json: any): PatchedLongTermAbsenceEditRequest {
    return PatchedLongTermAbsenceEditRequestFromJSONTyped(json, false);
}

export function PatchedLongTermAbsenceEditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLongTermAbsenceEditRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'student': !exists(json, 'student') ? undefined : json['student'],
        'startDate': !exists(json, 'start_date') ? undefined : (new Date(json['start_date'])),
        'endDate': !exists(json, 'end_date') ? undefined : (new Date(json['end_date'])),
        'reason': !exists(json, 'reason') ? undefined : json['reason'],
    };
}

export function PatchedLongTermAbsenceEditRequestToJSON(value?: PatchedLongTermAbsenceEditRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student': value.student,
        'start_date': value.startDate === undefined ? undefined : (value.startDate.toISOString().substr(0,10)),
        'end_date': value.endDate === undefined ? undefined : (value.endDate.toISOString().substr(0,10)),
        'reason': value.reason,
    };
}

