/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedSubjectRequest
 */
export interface PatchedSubjectRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedSubjectRequest
     */
    name?: string;
}

export function PatchedSubjectRequestFromJSON(json: any): PatchedSubjectRequest {
    return PatchedSubjectRequestFromJSONTyped(json, false);
}

export function PatchedSubjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSubjectRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function PatchedSubjectRequestToJSON(value?: PatchedSubjectRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

