/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedWorksheetEditRequest
 */
export interface PatchedWorksheetEditRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedWorksheetEditRequest
     */
    subjectLevel?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedWorksheetEditRequest
     */
    set?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedWorksheetEditRequest
     */
    quantity?: number;
}

export function PatchedWorksheetEditRequestFromJSON(json: any): PatchedWorksheetEditRequest {
    return PatchedWorksheetEditRequestFromJSONTyped(json, false);
}

export function PatchedWorksheetEditRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedWorksheetEditRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'subjectLevel': !exists(json, 'subject_level') ? undefined : json['subject_level'],
        'set': !exists(json, 'set') ? undefined : json['set'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
    };
}

export function PatchedWorksheetEditRequestToJSON(value?: PatchedWorksheetEditRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'subject_level': value.subjectLevel,
        'set': value.set,
        'quantity': value.quantity,
    };
}

