/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReturnItemRequest
 */
export interface ReturnItemRequest {
    /**
     * 
     * @type {number}
     * @memberof ReturnItemRequest
     */
    quantity: number;
}

export function ReturnItemRequestFromJSON(json: any): ReturnItemRequest {
    return ReturnItemRequestFromJSONTyped(json, false);
}

export function ReturnItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnItemRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
    };
}

export function ReturnItemRequestToJSON(value?: ReturnItemRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantity': value.quantity,
    };
}

