/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for the admin to set a password for an account.
 * @export
 * @interface SetPasswordRequest
 */
export interface SetPasswordRequest {
    /**
     * 
     * @type {number}
     * @memberof SetPasswordRequest
     */
    staffId: number;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof SetPasswordRequest
     */
    confirmNewPassword: string;
}

export function SetPasswordRequestFromJSON(json: any): SetPasswordRequest {
    return SetPasswordRequestFromJSONTyped(json, false);
}

export function SetPasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPasswordRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'staffId': json['staff_id'],
        'newPassword': json['new_password'],
        'confirmNewPassword': json['confirm_new_password'],
    };
}

export function SetPasswordRequestToJSON(value?: SetPasswordRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'staff_id': value.staffId,
        'new_password': value.newPassword,
        'confirm_new_password': value.confirmNewPassword,
    };
}

