/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressRequest,
    AddressRequestFromJSON,
    AddressRequestFromJSONTyped,
    AddressRequestToJSON,
} from './AddressRequest';
import {
    GradeEnum,
    GradeEnumFromJSON,
    GradeEnumFromJSONTyped,
    GradeEnumToJSON,
} from './GradeEnum';

/**
 * 
 * @export
 * @interface StudentRequest
 */
export interface StudentRequest {
    /**
     * 
     * @type {number}
     * @memberof StudentRequest
     */
    kSisId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentRequest
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {Date}
     * @memberof StudentRequest
     */
    joinDate?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof StudentRequest
     */
    leaveDate?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    phoneNumber: string;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    school: string;
    /**
     * 
     * @type {GradeEnum}
     * @memberof StudentRequest
     */
    grade: GradeEnum;
    /**
     * 
     * @type {AddressRequest}
     * @memberof StudentRequest
     */
    address: AddressRequest;
    /**
     * 
     * @type {string}
     * @memberof StudentRequest
     */
    email: string;
}

export function StudentRequestFromJSON(json: any): StudentRequest {
    return StudentRequestFromJSONTyped(json, false);
}

export function StudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'kSisId': !exists(json, 'k_sis_id') ? undefined : json['k_sis_id'],
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'dateOfBirth': (new Date(json['date_of_birth'])),
        'joinDate': !exists(json, 'join_date') ? undefined : (json['join_date'] === null ? null : new Date(json['join_date'])),
        'leaveDate': !exists(json, 'leave_date') ? undefined : (json['leave_date'] === null ? null : new Date(json['leave_date'])),
        'phoneNumber': json['phone_number'],
        'school': json['school'],
        'grade': GradeEnumFromJSON(json['grade']),
        'address': AddressRequestFromJSON(json['address']),
        'email': json['email'],
    };
}

export function StudentRequestToJSON(value?: StudentRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_sis_id': value.kSisId,
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'date_of_birth': (value.dateOfBirth.toISOString().substr(0,10)),
        'join_date': value.joinDate === undefined ? undefined : (value.joinDate === null ? null : value.joinDate.toISOString().substr(0,10)),
        'leave_date': value.leaveDate === undefined ? undefined : (value.leaveDate === null ? null : value.leaveDate.toISOString().substr(0,10)),
        'phone_number': value.phoneNumber,
        'school': value.school,
        'grade': GradeEnumToJSON(value.grade),
        'address': AddressRequestToJSON(value.address),
        'email': value.email,
    };
}

