/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ContactList,
    ContactListFromJSON,
    ContactListFromJSONTyped,
    ContactListToJSON,
} from './ContactList';

/**
 * Serializer for retrieving student contact relations
 * @export
 * @interface StudentGetContacts
 */
export interface StudentGetContacts {
    /**
     * 
     * @type {ContactList}
     * @memberof StudentGetContacts
     */
    contactId: ContactList;
    /**
     * 
     * @type {string}
     * @memberof StudentGetContacts
     */
    relationship: string;
}

export function StudentGetContactsFromJSON(json: any): StudentGetContacts {
    return StudentGetContactsFromJSONTyped(json, false);
}

export function StudentGetContactsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentGetContacts {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'contactId': ContactListFromJSON(json['contact_id']),
        'relationship': json['relationship'],
    };
}

export function StudentGetContactsToJSON(value?: StudentGetContacts | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'contact_id': ContactListToJSON(value.contactId),
        'relationship': value.relationship,
    };
}

