/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Serializer for creating a record sheet for a specific student.
 * @export
 * @interface StudentRecordSheetRequest
 */
export interface StudentRecordSheetRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof StudentRecordSheetRequest
     */
    studentId: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof StudentRecordSheetRequest
     */
    subjectLevelId: number | null;
    /**
     * 
     * @type {Date}
     * @memberof StudentRecordSheetRequest
     */
    startDate: Date;
    /**
     * 
     * @type {number}
     * @memberof StudentRecordSheetRequest
     */
    numDays?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentRecordSheetRequest
     */
    sheetsPerDay?: number;
    /**
     * 
     * @type {number}
     * @memberof StudentRecordSheetRequest
     */
    completionTime: number;
    /**
     * 
     * @type {string}
     * @memberof StudentRecordSheetRequest
     */
    type: string;
}

export function StudentRecordSheetRequestFromJSON(json: any): StudentRecordSheetRequest {
    return StudentRecordSheetRequestFromJSONTyped(json, false);
}

export function StudentRecordSheetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentRecordSheetRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'studentId': json['student_id'],
        'subjectLevelId': json['subject_level_id'],
        'startDate': (new Date(json['start_date'])),
        'numDays': !exists(json, 'num_days') ? undefined : json['num_days'],
        'sheetsPerDay': !exists(json, 'sheets_per_day') ? undefined : json['sheets_per_day'],
        'completionTime': json['completion_time'],
        'type': json['type'],
    };
}

export function StudentRecordSheetRequestToJSON(value?: StudentRecordSheetRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'student_id': value.studentId,
        'subject_level_id': value.subjectLevelId,
        'start_date': (value.startDate.toISOString().substr(0,10)),
        'num_days': value.numDays,
        'sheets_per_day': value.sheetsPerDay,
        'completion_time': value.completionTime,
        'type': value.type,
    };
}

