/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GradeEnum,
    GradeEnumFromJSON,
    GradeEnumFromJSONTyped,
    GradeEnumToJSON,
} from './GradeEnum';

/**
 * Serializer for students which only includes their name and IDs.
 * @export
 * @interface StudentList
 */
export interface StudentList {
    /**
     * 
     * @type {number}
     * @memberof StudentList
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof StudentList
     */
    kSisId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StudentList
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StudentList
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentList
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentList
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {string}
     * @memberof StudentList
     */
    school: string;
    /**
     * 
     * @type {GradeEnum}
     * @memberof StudentList
     */
    grade: GradeEnum;
}

export function StudentListFromJSON(json: any): StudentList {
    return StudentListFromJSONTyped(json, false);
}

export function StudentListFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kSisId': !exists(json, 'k_sis_id') ? undefined : json['k_sis_id'],
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'dateOfBirth': (new Date(json['date_of_birth'])),
        'school': json['school'],
        'grade': GradeEnumFromJSON(json['grade']),
    };
}

export function StudentListToJSON(value?: StudentList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_sis_id': value.kSisId,
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'date_of_birth': (value.dateOfBirth.toISOString().substr(0,10)),
        'school': value.school,
        'grade': GradeEnumToJSON(value.grade),
    };
}

