/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GradeEnum,
    GradeEnumFromJSON,
    GradeEnumFromJSONTyped,
    GradeEnumToJSON,
} from './GradeEnum';

/**
 * Serializer for listing gdpr deleted student instances.
 * @export
 * @interface StudentDeleted
 */
export interface StudentDeleted {
    /**
     * 
     * @type {number}
     * @memberof StudentDeleted
     */
    readonly id: number;
    /**
     * 
     * @type {number}
     * @memberof StudentDeleted
     */
    kSisId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StudentDeleted
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof StudentDeleted
     */
    middleName?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentDeleted
     */
    lastName: string;
    /**
     * 
     * @type {Date}
     * @memberof StudentDeleted
     */
    dateOfBirth: Date;
    /**
     * 
     * @type {string}
     * @memberof StudentDeleted
     */
    school: string;
    /**
     * 
     * @type {GradeEnum}
     * @memberof StudentDeleted
     */
    grade: GradeEnum;
    /**
     * 
     * @type {Date}
     * @memberof StudentDeleted
     */
    deletedAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof StudentDeleted
     */
    readonly permanentDeletionDate: Date;
}

export function StudentDeletedFromJSON(json: any): StudentDeleted {
    return StudentDeletedFromJSONTyped(json, false);
}

export function StudentDeletedFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentDeleted {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'kSisId': !exists(json, 'k_sis_id') ? undefined : json['k_sis_id'],
        'firstName': json['first_name'],
        'middleName': !exists(json, 'middle_name') ? undefined : json['middle_name'],
        'lastName': json['last_name'],
        'dateOfBirth': (new Date(json['date_of_birth'])),
        'school': json['school'],
        'grade': GradeEnumFromJSON(json['grade']),
        'deletedAt': !exists(json, 'deleted_at') ? undefined : (json['deleted_at'] === null ? null : new Date(json['deleted_at'])),
        'permanentDeletionDate': (new Date(json['permanent_deletion_date'])),
    };
}

export function StudentDeletedToJSON(value?: StudentDeleted | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'k_sis_id': value.kSisId,
        'first_name': value.firstName,
        'middle_name': value.middleName,
        'last_name': value.lastName,
        'date_of_birth': (value.dateOfBirth.toISOString().substr(0,10)),
        'school': value.school,
        'grade': GradeEnumToJSON(value.grade),
        'deleted_at': value.deletedAt === undefined ? undefined : (value.deletedAt === null ? null : value.deletedAt.toISOString()),
    };
}

