/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubjectRemoveLevelRequest
 */
export interface SubjectRemoveLevelRequest {
    /**
     * 
     * @type {number}
     * @memberof SubjectRemoveLevelRequest
     */
    id: number;
}

export function SubjectRemoveLevelRequestFromJSON(json: any): SubjectRemoveLevelRequest {
    return SubjectRemoveLevelRequestFromJSONTyped(json, false);
}

export function SubjectRemoveLevelRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectRemoveLevelRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SubjectRemoveLevelRequestToJSON(value?: SubjectRemoveLevelRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

