/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum Type3beEnum {
    W = 'W',
    R = 'R'
}

export function Type3beEnumFromJSON(json: any): Type3beEnum {
    return Type3beEnumFromJSONTyped(json, false);
}

export function Type3beEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Type3beEnum {
    return json as Type3beEnum;
}

export function Type3beEnumToJSON(value?: Type3beEnum | null): any {
    return value as any;
}

