/* tslint:disable */
/* eslint-disable */
/**
 * Kumon App - Backend API
 * Backend API for the Kumon Centre Management app.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Type3beEnum,
    Type3beEnumFromJSON,
    Type3beEnumFromJSONTyped,
    Type3beEnumToJSON,
} from './Type3beEnum';

/**
 * 
 * @export
 * @interface WorksheetLog
 */
export interface WorksheetLog {
    /**
     * 
     * @type {number}
     * @memberof WorksheetLog
     */
    staffId?: number | null;
    /**
     * 
     * @type {Type3beEnum}
     * @memberof WorksheetLog
     */
    type: Type3beEnum;
    /**
     * 
     * @type {number}
     * @memberof WorksheetLog
     */
    quantity: number;
    /**
     * 
     * @type {Date}
     * @memberof WorksheetLog
     */
    readonly createdAt: Date;
}

export function WorksheetLogFromJSON(json: any): WorksheetLog {
    return WorksheetLogFromJSONTyped(json, false);
}

export function WorksheetLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorksheetLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'staffId': !exists(json, 'staff_id') ? undefined : json['staff_id'],
        'type': Type3beEnumFromJSON(json['type']),
        'quantity': json['quantity'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function WorksheetLogToJSON(value?: WorksheetLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'staff_id': value.staffId,
        'type': Type3beEnumToJSON(value.type),
        'quantity': value.quantity,
    };
}

